import textileImg from "@/assets/cat-textile.jpg";
import plasticImg from "@/assets/cat-plastic.jpg";
import paperImg from "@/assets/cat-paper.jpg";
import metalImg from "@/assets/cat-metal.jpg";
import woodImg from "@/assets/cat-wood.jpg";
import glassImg from "@/assets/cat-glass-recycled.png";
import rubberImg from "@/assets/cat-rubber.jpg";
import constructionImg from "@/assets/cat-construction.jpg";
import industrialImg from "@/assets/cat-industrial.jpg";
import otherImg from "@/assets/cat-other.jpg";

export type CategoryId =
  | "textile"
  | "plastic"
  | "paper"
  | "metal"
  | "wood"
  | "glass"
  | "rubber"
  | "construction"
  | "industrial"
  | "other";

export interface Category {
  id: CategoryId;
  name: string;
  blurb: string;
  image: string;
  active: boolean;
  tons: number;
}

export const CATEGORIES: Category[] = [
  {
    id: "textile",
    name: "Textile & Fabric",
    blurb: "Fabric, denim, yarn, leather, thread, zippers, buttons",
    image: textileImg,
    active: true,
    tons: 4.2,
  },
  {
    id: "plastic",
    name: "Plastic",
    blurb: "Bottles, containers, packaging, plastic sheets, scraps",
    image: plasticImg,
    active: true,
    tons: 3.1,
  },
  {
    id: "paper",
    name: "Paper & Cardboard",
    blurb: "Boxes, paper rolls, sheets, packaging, paper scraps",
    image: paperImg,
    active: true,
    tons: 2.3,
  },
  {
    id: "metal",
    name: "Metal",
    blurb: "Aluminum, steel, metal sheets, wires, metal offcuts",
    image: metalImg,
    active: true,
    tons: 1.8,
  },
  {
    id: "wood",
    name: "Wood",
    blurb: "Timber, plywood, pallets, crates, wood offcuts",
    image: woodImg,
    active: true,
    tons: 0.7,
  },
  {
    id: "glass",
    name: "Glass",
    blurb: "Bottles, jars, containers, glass sheets",
    image: glassImg,
    active: true,
    tons: 0.2,
  },
  {
    id: "rubber",
    name: "Rubber",
    blurb: "Rubber sheets, scraps, offcuts",
    image: rubberImg,
    active: true,
    tons: 0.1,
  },
  {
    id: "construction",
    name: "Construction",
    blurb: "Tiles, pipes, plywood, building-material surplus",
    image: constructionImg,
    active: true,
    tons: 1.1,
  },
  {
    id: "industrial",
    name: "Industrial Components",
    blurb: "Fasteners, containers, accessories, production components",
    image: industrialImg,
    active: true,
    tons: 0.6,
  },
  {
    id: "other",
    name: "Other",
    blurb: "Other legitimate surplus or recyclable business materials",
    image: otherImg,
    active: true,
    tons: 0.3,
  },
];

export const categoryName = (id: CategoryId) =>
  CATEGORIES.find((c) => c.id === id)?.name ?? "Other";
export const categoryImage = (id: CategoryId) =>
  CATEGORIES.find((c) => c.id === id)?.image ?? otherImg;

export const MATERIAL_TYPES = [
  "Reusable Surplus",
  "Production Surplus",
  "Offcut",
  "Excess Inventory",
  "Recyclable Material",
  "Scrap Material",
  "Packaging Surplus",
  "Unused Stock",
] as const;
export type MaterialType = (typeof MATERIAL_TYPES)[number];

export const CONDITIONS = [
  "New / Unused",
  "Like New",
  "Good",
  "Minor Defect",
  "Used",
  "Scrap / Requires Processing",
] as const;
export type Condition = (typeof CONDITIONS)[number];

export const LOCATIONS = [
  "Yangon",
  "Mandalay",
  "Bago",
  "Mawlamyine",
  "Taunggyi",
  "Pathein",
] as const;

export interface Business {
  id: string;
  userId?: string;
  name: string;
  initials: string;
  industry: string;
  location: string;
  verified: boolean;
  rating: number;
  transactions: number;
  since: number;
  categories: CategoryId[];
  description: string;
  contact: { person: string; phone: string; email: string; address: string };
  hours: string;
  website: string;
  avatarUrl?: string;
  bannerUrl?: string;
  socialLinks?: {
    facebook: string;
    linkedin: string;
    instagram: string;
  };
}

export const BUSINESSES: Business[] = [
  {
    id: "green-stitch",
    userId: "user-green-stitch",
    name: "Green Stitch Textile Co.",
    initials: "GS",
    industry: "Garment Manufacturing",
    location: "Yangon",
    verified: true,
    rating: 4.8,
    transactions: 32,
    since: 2016,
    categories: ["textile"],
    description:
      "A CMP garment factory in Hlaing Tharyar producing woven and knit apparel for export. We list surplus fabric rolls, denim offcuts and trims every production cycle instead of discarding them.",
    contact: {
      person: "Daw Khin Myat",
      phone: "+95 9 77 000 1120",
      email: "surplus@greenstitch.com.mm",
      address: "No. 42, Industrial Zone 3, Hlaing Tharyar, Yangon",
    },
    hours: "Mon–Sat, 9:00 – 17:30",
    website: "greenstitch.com.mm",
  },
  {
    id: "yangon-circular-plastics",
    name: "Yangon Circular Plastics",
    initials: "YC",
    industry: "Plastic Reprocessing",
    location: "Yangon",
    verified: true,
    rating: 4.9,
    transactions: 58,
    since: 2014,
    categories: ["plastic", "industrial"],
    description:
      "Collection, sorting and baling of post-industrial plastics. We supply washed PET flake, HDPE regrind and clean plastic film to manufacturers across Myanmar.",
    contact: {
      person: "U Zaw Min Htet",
      phone: "+95 9 42 118 8830",
      email: "sales@ycplastics.com.mm",
      address: "Plot 18, Shwe Pyi Thar Industrial Zone, Yangon",
    },
    hours: "Mon–Sat, 8:00 – 18:00",
    website: "ycplastics.com.mm",
  },
  {
    id: "ecobox-myanmar",
    name: "EcoBox Myanmar",
    initials: "EB",
    industry: "Packaging & Corrugation",
    location: "Mandalay",
    verified: true,
    rating: 4.7,
    transactions: 41,
    since: 2018,
    categories: ["paper"],
    description:
      "Corrugated packaging producer in Mandalay. We list surplus boxes, trimmed sheets and kraft paper rolls from over-runs and cancelled orders.",
    contact: {
      person: "Ko Aung Kyaw",
      phone: "+95 9 20 445 7712",
      email: "hello@ecoboxmm.com",
      address: "Corner of 62nd & Theikpan St, Pyigyitagon, Mandalay",
    },
    hours: "Mon–Fri, 8:30 – 17:00",
    website: "ecoboxmm.com",
  },
  {
    id: "myanmar-metal-recovery",
    name: "Myanmar Metal Recovery",
    initials: "MM",
    industry: "Metal Recovery & Trading",
    location: "Bago",
    verified: true,
    rating: 4.6,
    transactions: 47,
    since: 2012,
    categories: ["metal", "industrial"],
    description:
      "Sorting and trading of aluminium, steel and copper production surplus from factories in the Bago and Yangon corridors.",
    contact: {
      person: "U Thet Naing",
      phone: "+95 9 79 330 2211",
      email: "trade@mmmetal.com.mm",
      address: "Mile 46, Yangon–Mandalay Road, Bago",
    },
    hours: "Mon–Sat, 8:00 – 17:00",
    website: "mmmetal.com.mm",
  },
  {
    id: "greenwood-manufacturing",
    name: "GreenWood Manufacturing",
    initials: "GW",
    industry: "Furniture & Woodwork",
    location: "Yangon",
    verified: true,
    rating: 4.8,
    transactions: 26,
    since: 2017,
    categories: ["wood", "construction"],
    description:
      "Furniture workshop producing hardwood and plywood pieces. Offcuts, short lengths and used pallets are listed weekly for makers and small manufacturers.",
    contact: {
      person: "Ma Su Yadanar",
      phone: "+95 9 96 552 4400",
      email: "workshop@greenwood.mm",
      address: "No. 7, Dagon Seikkan Industrial Zone, Yangon",
    },
    hours: "Mon–Sat, 9:00 – 18:00",
    website: "greenwood.mm",
  },
  {
    id: "yangon-glass-supply",
    name: "Yangon Glass Supply",
    initials: "YG",
    industry: "Glass Containers & Sheets",
    location: "Yangon",
    verified: true,
    rating: 4.5,
    transactions: 19,
    since: 2019,
    categories: ["glass"],
    description:
      "Supplier of returnable glass bottles, jars and cut sheet surplus to beverage, food and interior businesses.",
    contact: {
      person: "U Myo Set",
      phone: "+95 9 45 220 6633",
      email: "orders@yangonglass.mm",
      address: "Yankin Township, Yangon",
    },
    hours: "Mon–Fri, 9:00 – 17:00",
    website: "yangonglass.mm",
  },
  {
    id: "ecorubber-industries",
    name: "EcoRubber Industries",
    initials: "ER",
    industry: "Rubber Processing",
    location: "Mandalay",
    verified: false,
    rating: 4.3,
    transactions: 11,
    since: 2021,
    categories: ["rubber"],
    description:
      "Rubber sheet and gasket producer. Offcuts and trimmed sheet surplus are available for re-cutting, matting and industrial padding uses.",
    contact: {
      person: "Ko Nay Lin",
      phone: "+95 9 25 118 0099",
      email: "info@ecorubber.mm",
      address: "Industrial Zone 2, Amarapura, Mandalay",
    },
    hours: "Mon–Sat, 8:30 – 17:30",
    website: "ecorubber.mm",
  },
  {
    id: "circularbuild-myanmar",
    name: "CircularBuild Myanmar",
    initials: "CB",
    industry: "Construction Materials",
    location: "Yangon",
    verified: true,
    rating: 4.7,
    transactions: 23,
    since: 2020,
    categories: ["construction", "wood", "metal"],
    description:
      "Contractor and materials trader listing unused tiles, pipes, plywood and site surplus from completed projects across Yangon.",
    contact: {
      person: "U Kyaw Swar",
      phone: "+95 9 78 664 1180",
      email: "surplus@circularbuild.mm",
      address: "Thaketa Township, Yangon",
    },
    hours: "Mon–Sat, 8:00 – 17:00",
    website: "circularbuild.mm",
  },
];

export const businessById = (id: string) => BUSINESSES.find((b) => b.id === id);

export interface Listing {
  id: string;
  title: string;
  category: CategoryId;
  materialType: MaterialType;
  condition: Condition;
  composition: string;
  quantity: number;
  unit: string;
  price: number | null;
  priceUnit: string;
  minOrder: string;
  location: string;
  availableFrom: string;
  sellerId: string;
  requiresProcessing: boolean;
  pickupAvailable: boolean;
  featured?: boolean;
  views: number;
  inquiries: number;
  popularity: number;
  postedDaysAgo: number;
  status: "Active" | "Reserved" | "Sold Out" | "Hidden";
  description: string;
  uses: string[];
}

export const LISTINGS: Listing[] = [
  {
    id: "cotton-fabric-surplus",
    title: "Cotton Fabric Surplus",
    category: "textile",
    materialType: "Production Surplus",
    condition: "New / Unused",
    composition: "100% cotton twill, 180 GSM, mixed dye lots",
    quantity: 85,
    unit: "kg",
    price: 4500,
    priceUnit: "kg",
    minOrder: "10 kg",
    location: "Yangon",
    availableFrom: "Available now",
    sellerId: "green-stitch",
    requiresProcessing: false,
    pickupAvailable: true,
    featured: true,
    views: 1240,
    inquiries: 18,
    popularity: 96,
    postedDaysAgo: 2,
    status: "Active",
    description:
      "Unused cotton twill remaining from a cancelled export order. Rolls are stored indoors, wrapped and free from moisture damage. Mixed dye lots in navy, khaki and off-white.",
    uses: ["Small-batch garment production", "Bag and accessory manufacturing", "Uniform production", "Craft and sampling"],
  },
  {
    id: "denim-offcuts",
    title: "Denim Offcuts",
    category: "textile",
    materialType: "Offcut",
    condition: "Good",
    composition: "Cotton denim 12oz, cutting-table offcuts",
    quantity: 240,
    unit: "kg",
    price: 1800,
    priceUnit: "kg",
    minOrder: "20 kg",
    location: "Yangon",
    availableFrom: "Available now",
    sellerId: "green-stitch",
    requiresProcessing: false,
    pickupAvailable: true,
    views: 860,
    inquiries: 12,
    popularity: 81,
    postedDaysAgo: 5,
    status: "Active",
    description:
      "Weekly denim offcuts from our cutting floor, baled and sorted by shade. Piece sizes mostly between 20cm and 60cm.",
    uses: ["Patchwork products", "Bags and pouches", "Industrial wipes", "Craft manufacturing"],
  },
  {
    id: "polyester-thread-cones",
    title: "Polyester Thread Cones",
    category: "textile",
    materialType: "Excess Inventory",
    condition: "New / Unused",
    composition: "40/2 spun polyester, 5,000m cones",
    quantity: 320,
    unit: "cones",
    price: 1200,
    priceUnit: "unit",
    minOrder: "50 cones",
    location: "Yangon",
    availableFrom: "Available now",
    sellerId: "green-stitch",
    requiresProcessing: false,
    pickupAvailable: true,
    views: 410,
    inquiries: 6,
    popularity: 62,
    postedDaysAgo: 9,
    status: "Active",
    description: "Surplus thread cones in white, black and grey. Sealed, stored on racks, unopened cartons.",
    uses: ["Garment sewing", "Bag manufacturing", "Tailoring workshops"],
  },
  {
    id: "metal-zippers",
    title: "Metal Zippers & Trims",
    category: "textile",
    materialType: "Unused Stock",
    condition: "New / Unused",
    composition: "Brass #5 zippers, 18cm–60cm, assorted",
    quantity: 6400,
    unit: "pieces",
    price: 220,
    priceUnit: "unit",
    minOrder: "500 pieces",
    location: "Yangon",
    availableFrom: "Available now",
    sellerId: "green-stitch",
    requiresProcessing: false,
    pickupAvailable: true,
    views: 300,
    inquiries: 4,
    popularity: 54,
    postedDaysAgo: 14,
    status: "Active",
    description: "Unused zipper stock from discontinued styles. Packed in polybags of 100.",
    uses: ["Garment production", "Bag manufacturing", "Repair services"],
  },
  {
    id: "pet-plastic-scrap",
    title: "PET Plastic Scrap",
    category: "plastic",
    materialType: "Recyclable Material",
    condition: "Scrap / Requires Processing",
    composition: "Post-consumer PET bottles, baled, label-mixed",
    quantity: 550,
    unit: "kg",
    price: 600,
    priceUnit: "kg",
    minOrder: "100 kg",
    location: "Yangon",
    availableFrom: "Available now",
    sellerId: "yangon-circular-plastics",
    requiresProcessing: true,
    pickupAvailable: true,
    featured: true,
    views: 2010,
    inquiries: 27,
    popularity: 99,
    postedDaysAgo: 1,
    status: "Active",
    description:
      "Baled clear and light-blue PET collected from beverage distributors. Requires washing and flaking before reprocessing. Bale weight approx. 55kg.",
    uses: ["Plastic reprocessing", "Manufacturing inputs", "Packaging production", "Fibre production"],
  },
  {
    id: "plastic-packaging-surplus",
    title: "Plastic Packaging Surplus",
    category: "plastic",
    materialType: "Packaging Surplus",
    condition: "New / Unused",
    composition: "LDPE poly bags and shrink film, printed & plain",
    quantity: 180,
    unit: "kg",
    price: 2200,
    priceUnit: "kg",
    minOrder: "20 kg",
    location: "Yangon",
    availableFrom: "Available now",
    sellerId: "yangon-circular-plastics",
    requiresProcessing: false,
    pickupAvailable: true,
    featured: true,
    views: 740,
    inquiries: 9,
    popularity: 78,
    postedDaysAgo: 4,
    status: "Active",
    description: "Unused packaging film and bags from cancelled orders. Plain stock suitable for immediate reuse.",
    uses: ["Product packaging", "Shipping protection", "Storage"],
  },
  {
    id: "hdpe-plastic-sheets",
    title: "HDPE Plastic Sheets",
    category: "plastic",
    materialType: "Offcut",
    condition: "Good",
    composition: "HDPE sheet 5mm, offcut panels",
    quantity: 95,
    unit: "sheets",
    price: 6500,
    priceUnit: "unit",
    minOrder: "10 sheets",
    location: "Yangon",
    availableFrom: "Available now",
    sellerId: "yangon-circular-plastics",
    requiresProcessing: false,
    pickupAvailable: true,
    views: 380,
    inquiries: 5,
    popularity: 58,
    postedDaysAgo: 11,
    status: "Reserved",
    description: "Cut panels from a fabrication run, sizes between 40x60cm and 90x120cm.",
    uses: ["Fabrication", "Cutting boards", "Machine guards", "Signage"],
  },
  {
    id: "corrugated-cardboard-boxes",
    title: "Corrugated Cardboard Boxes",
    category: "paper",
    materialType: "Reusable Surplus",
    condition: "Like New",
    composition: "3-ply corrugated, 40x30x25cm",
    quantity: 1200,
    unit: "boxes",
    price: 300,
    priceUnit: "unit",
    minOrder: "100 boxes",
    location: "Mandalay",
    availableFrom: "Available now",
    sellerId: "ecobox-myanmar",
    requiresProcessing: false,
    pickupAvailable: true,
    featured: true,
    views: 1580,
    inquiries: 21,
    popularity: 94,
    postedDaysAgo: 3,
    status: "Active",
    description:
      "Over-run cartons from a completed order, flat-packed and stored dry. Minor print on one side, structurally as-new.",
    uses: ["Shipping boxes", "Packaging", "Storage", "E-commerce fulfilment"],
  },
  {
    id: "kraft-paper-rolls",
    title: "Kraft Paper Rolls",
    category: "paper",
    materialType: "Excess Inventory",
    condition: "New / Unused",
    composition: "120 GSM kraft, 90cm width rolls",
    quantity: 42,
    unit: "rolls",
    price: 38000,
    priceUnit: "unit",
    minOrder: "5 rolls",
    location: "Mandalay",
    availableFrom: "Available now",
    sellerId: "ecobox-myanmar",
    requiresProcessing: false,
    pickupAvailable: true,
    views: 520,
    inquiries: 7,
    popularity: 66,
    postedDaysAgo: 8,
    status: "Active",
    description: "Unused kraft rolls surplus to current production planning.",
    uses: ["Wrapping and void fill", "Paper bag production", "Printing"],
  },
  {
    id: "cardboard-sheets",
    title: "Cardboard Sheet Trim",
    category: "paper",
    materialType: "Offcut",
    condition: "Good",
    composition: "Corrugated trim sheets, mixed sizes",
    quantity: 900,
    unit: "kg",
    price: 250,
    priceUnit: "kg",
    minOrder: "100 kg",
    location: "Mandalay",
    availableFrom: "From 20 Aug",
    sellerId: "ecobox-myanmar",
    requiresProcessing: true,
    pickupAvailable: true,
    views: 340,
    inquiries: 3,
    popularity: 49,
    postedDaysAgo: 16,
    status: "Active",
    description: "Trim from our corrugator, baled. Suitable for repulping or protective layering.",
    uses: ["Paper recycling", "Protective packing", "Layer pads"],
  },
  {
    id: "aluminum-offcuts",
    title: "Aluminum Offcuts",
    category: "metal",
    materialType: "Recyclable Material",
    condition: "Scrap / Requires Processing",
    composition: "6063 aluminium extrusion offcuts, clean",
    quantity: 250,
    unit: "kg",
    price: 3800,
    priceUnit: "kg",
    minOrder: "50 kg",
    location: "Bago",
    availableFrom: "Available now",
    sellerId: "myanmar-metal-recovery",
    requiresProcessing: true,
    pickupAvailable: true,
    featured: true,
    views: 970,
    inquiries: 14,
    popularity: 88,
    postedDaysAgo: 6,
    status: "Active",
    description: "Clean extrusion offcuts, sorted and free of steel contamination. Weighed on certified scale at pickup.",
    uses: ["Aluminium smelting", "Casting inputs", "Fabrication components"],
  },
  {
    id: "steel-offcuts",
    title: "Steel Plate Offcuts",
    category: "metal",
    materialType: "Offcut",
    condition: "Good",
    composition: "Mild steel plate 3–8mm, laser-cut remnants",
    quantity: 640,
    unit: "kg",
    price: 1450,
    priceUnit: "kg",
    minOrder: "100 kg",
    location: "Bago",
    availableFrom: "Available now",
    sellerId: "myanmar-metal-recovery",
    requiresProcessing: false,
    pickupAvailable: true,
    views: 610,
    inquiries: 8,
    popularity: 71,
    postedDaysAgo: 10,
    status: "Active",
    description: "Usable plate remnants from laser cutting, sorted by thickness.",
    uses: ["Metal fabrication", "Bracket production", "Workshop stock"],
  },
  {
    id: "copper-wire-scrap",
    title: "Copper Wire Scrap",
    category: "metal",
    materialType: "Scrap Material",
    condition: "Scrap / Requires Processing",
    composition: "Insulated copper wire, mixed gauges",
    quantity: 120,
    unit: "kg",
    price: 9800,
    priceUnit: "kg",
    minOrder: "20 kg",
    location: "Bago",
    availableFrom: "Available now",
    sellerId: "myanmar-metal-recovery",
    requiresProcessing: true,
    pickupAvailable: false,
    views: 720,
    inquiries: 11,
    popularity: 77,
    postedDaysAgo: 7,
    status: "Active",
    description: "Insulated wire requiring stripping before smelting. Delivery available within Bago and Yangon.",
    uses: ["Copper recovery", "Electrical component manufacturing"],
  },
  {
    id: "wood-offcuts",
    title: "Wood Offcuts",
    category: "wood",
    materialType: "Reusable Surplus",
    condition: "Good",
    composition: "Hardwood and rubberwood, 20–80cm lengths",
    quantity: 180,
    unit: "kg",
    price: null,
    priceUnit: "kg",
    minOrder: "20 kg",
    location: "Yangon",
    availableFrom: "Available now",
    sellerId: "greenwood-manufacturing",
    requiresProcessing: false,
    pickupAvailable: true,
    views: 880,
    inquiries: 13,
    popularity: 84,
    postedDaysAgo: 2,
    status: "Active",
    description:
      "Kiln-dried offcuts from furniture production. Price negotiable depending on volume and collection schedule.",
    uses: ["Furniture components", "Packaging", "Crafts", "Small product manufacturing"],
  },
  {
    id: "wooden-pallets",
    title: "Wooden Pallets",
    category: "wood",
    materialType: "Reusable Surplus",
    condition: "Used",
    composition: "Standard 120x100cm four-way pallets",
    quantity: 260,
    unit: "pallets",
    price: 4500,
    priceUnit: "unit",
    minOrder: "20 pallets",
    location: "Yangon",
    availableFrom: "Available now",
    sellerId: "greenwood-manufacturing",
    requiresProcessing: false,
    pickupAvailable: true,
    views: 640,
    inquiries: 10,
    popularity: 73,
    postedDaysAgo: 12,
    status: "Active",
    description: "Used but structurally sound pallets, inspected before release. Repairable units priced lower.",
    uses: ["Warehouse handling", "Furniture upcycling", "Crating"],
  },
  {
    id: "plywood-sheets",
    title: "Plywood Sheet Surplus",
    category: "wood",
    materialType: "Excess Inventory",
    condition: "New / Unused",
    composition: "12mm commercial plywood, 4x8ft",
    quantity: 74,
    unit: "sheets",
    price: 32000,
    priceUnit: "unit",
    minOrder: "5 sheets",
    location: "Yangon",
    availableFrom: "Available now",
    sellerId: "greenwood-manufacturing",
    requiresProcessing: false,
    pickupAvailable: true,
    views: 430,
    inquiries: 6,
    popularity: 64,
    postedDaysAgo: 15,
    status: "Active",
    description: "Unused sheets from an over-ordered project. Stored flat and dry.",
    uses: ["Furniture", "Interior fit-out", "Crate production"],
  },
  {
    id: "glass-bottles",
    title: "Glass Bottles",
    category: "glass",
    materialType: "Reusable Surplus",
    condition: "Like New",
    composition: "330ml clear glass bottles, washed",
    quantity: 2000,
    unit: "pieces",
    price: 350,
    priceUnit: "unit",
    minOrder: "200 pieces",
    location: "Yangon",
    availableFrom: "Available now",
    sellerId: "yangon-glass-supply",
    requiresProcessing: false,
    pickupAvailable: true,
    views: 690,
    inquiries: 9,
    popularity: 75,
    postedDaysAgo: 4,
    status: "Active",
    description: "Washed and crated returnable bottles, suitable for beverage and sauce filling lines.",
    uses: ["Beverage bottling", "Sauces and condiments", "Retail packaging"],
  },
  {
    id: "glass-jars",
    title: "Glass Jars with Lids",
    category: "glass",
    materialType: "Unused Stock",
    condition: "New / Unused",
    composition: "250ml jars with metal twist lids",
    quantity: 1400,
    unit: "pieces",
    price: 520,
    priceUnit: "unit",
    minOrder: "100 pieces",
    location: "Yangon",
    availableFrom: "Available now",
    sellerId: "yangon-glass-supply",
    requiresProcessing: false,
    pickupAvailable: true,
    views: 350,
    inquiries: 4,
    popularity: 57,
    postedDaysAgo: 13,
    status: "Active",
    description: "Unused jar stock from a discontinued SKU. Lids included.",
    uses: ["Food packaging", "Cosmetics", "Retail products"],
  },
  {
    id: "glass-sheet-surplus",
    title: "Glass Sheet Surplus",
    category: "glass",
    materialType: "Production Surplus",
    condition: "Minor Defect",
    composition: "5mm float glass, cut sheets",
    quantity: 60,
    unit: "sheets",
    price: 14000,
    priceUnit: "unit",
    minOrder: "5 sheets",
    location: "Yangon",
    availableFrom: "From 22 Aug",
    sellerId: "yangon-glass-supply",
    requiresProcessing: false,
    pickupAvailable: false,
    views: 210,
    inquiries: 2,
    popularity: 43,
    postedDaysAgo: 18,
    status: "Active",
    description: "Cut sheets with minor edge chips. Suitable for framed or non-structural applications.",
    uses: ["Framing", "Interior fittings", "Display cases"],
  },
  {
    id: "rubber-sheet-offcuts",
    title: "Rubber Sheet Offcuts",
    category: "rubber",
    materialType: "Offcut",
    condition: "Scrap / Requires Processing",
    composition: "SBR rubber sheet 3–6mm, trimmed edges",
    quantity: 75,
    unit: "kg",
    price: 2500,
    priceUnit: "kg",
    minOrder: "15 kg",
    location: "Mandalay",
    availableFrom: "Available now",
    sellerId: "ecorubber-industries",
    requiresProcessing: true,
    pickupAvailable: true,
    views: 290,
    inquiries: 3,
    popularity: 47,
    postedDaysAgo: 9,
    status: "Active",
    description: "Edge trim from gasket cutting. Buyers typically re-cut smaller parts or granulate.",
    uses: ["Gasket re-cutting", "Matting", "Granulate inputs"],
  },
  {
    id: "rubber-sheets",
    title: "Industrial Rubber Sheets",
    category: "rubber",
    materialType: "Excess Inventory",
    condition: "New / Unused",
    composition: "Nitrile sheet 4mm, 1m x 1.2m",
    quantity: 48,
    unit: "sheets",
    price: 18000,
    priceUnit: "unit",
    minOrder: "4 sheets",
    location: "Mandalay",
    availableFrom: "Available now",
    sellerId: "ecorubber-industries",
    requiresProcessing: false,
    pickupAvailable: true,
    views: 240,
    inquiries: 2,
    popularity: 41,
    postedDaysAgo: 20,
    status: "Active",
    description: "Unused sheet stock held beyond planned production.",
    uses: ["Gaskets and seals", "Machine padding", "Flooring"],
  },
  {
    id: "ceramic-tiles",
    title: "Excess Ceramic Tiles",
    category: "construction",
    materialType: "Unused Stock",
    condition: "New / Unused",
    composition: "60x60cm matte porcelain, beige",
    quantity: 120,
    unit: "boxes",
    price: 25000,
    priceUnit: "box",
    minOrder: "5 boxes",
    location: "Yangon",
    availableFrom: "Available now",
    sellerId: "circularbuild-myanmar",
    requiresProcessing: false,
    pickupAvailable: true,
    featured: true,
    views: 830,
    inquiries: 12,
    popularity: 82,
    postedDaysAgo: 3,
    status: "Active",
    description: "Unused tiles left after a completed hotel fit-out. Same batch number, sealed boxes of 4 pieces.",
    uses: ["Interior fit-out", "Renovation projects", "Retail construction"],
  },
  {
    id: "unused-pvc-pipes",
    title: "Unused PVC Pipes",
    category: "construction",
    materialType: "Excess Inventory",
    condition: "New / Unused",
    composition: "PVC 4in pressure pipe, 4m lengths",
    quantity: 210,
    unit: "lengths",
    price: 11500,
    priceUnit: "unit",
    minOrder: "10 lengths",
    location: "Yangon",
    availableFrom: "Available now",
    sellerId: "circularbuild-myanmar",
    requiresProcessing: false,
    pickupAvailable: true,
    views: 460,
    inquiries: 6,
    popularity: 63,
    postedDaysAgo: 11,
    status: "Active",
    description: "Surplus pipe from a drainage package, stored under cover.",
    uses: ["Plumbing", "Drainage", "Irrigation"],
  },
  {
    id: "industrial-fasteners",
    title: "Assorted Industrial Fasteners",
    category: "industrial",
    materialType: "Excess Inventory",
    condition: "New / Unused",
    composition: "Stainless bolts, nuts, washers M6–M16",
    quantity: 340,
    unit: "kg",
    price: 5200,
    priceUnit: "kg",
    minOrder: "20 kg",
    location: "Yangon",
    availableFrom: "Available now",
    sellerId: "yangon-circular-plastics",
    requiresProcessing: false,
    pickupAvailable: true,
    views: 320,
    inquiries: 5,
    popularity: 56,
    postedDaysAgo: 17,
    status: "Active",
    description: "Mixed fastener stock sorted into labelled bins. Sold by weight per size band.",
    uses: ["Machinery assembly", "Workshop stock", "Maintenance"],
  },
  {
    id: "reusable-ibc-containers",
    title: "Reusable Plastic Containers",
    category: "industrial",
    materialType: "Packaging Surplus",
    condition: "Used",
    composition: "200L HDPE drums, food-grade, cleaned",
    quantity: 86,
    unit: "units",
    price: 21000,
    priceUnit: "unit",
    minOrder: "5 units",
    location: "Yangon",
    availableFrom: "Available now",
    sellerId: "yangon-circular-plastics",
    requiresProcessing: false,
    pickupAvailable: true,
    views: 510,
    inquiries: 8,
    popularity: 69,
    postedDaysAgo: 6,
    status: "Active",
    description: "Cleaned drums previously used for food-grade liquids. Lids and clamps included.",
    uses: ["Liquid storage", "Water tanks", "Agricultural use"],
  },
  {
    id: "mixed-office-paper",
    title: "Mixed Office Paper Surplus",
    category: "other",
    materialType: "Recyclable Material",
    condition: "Used",
    composition: "Sorted white and mixed office paper",
    quantity: 400,
    unit: "kg",
    price: 180,
    priceUnit: "kg",
    minOrder: "50 kg",
    location: "Yangon",
    availableFrom: "Available now",
    sellerId: "ecobox-myanmar",
    requiresProcessing: true,
    pickupAvailable: true,
    views: 180,
    inquiries: 2,
    popularity: 38,
    postedDaysAgo: 21,
    status: "Active",
    description: "Shredded and loose office paper collected from partner offices, baled monthly.",
    uses: ["Paper recycling", "Moulded pulp packaging"],
  },
];

export const listingById = (id: string) => LISTINGS.find((l) => l.id === id);
export const listingsBySeller = (sellerId: string) =>
  LISTINGS.filter((l) => l.sellerId === sellerId);
export const listingCountByCategory = (categoryId: CategoryId) =>
  LISTINGS.filter((listing) => listing.category === categoryId).length;

export interface WantedPost {
  id: string;
  title: string;
  category: CategoryId;
  quantity: string;
  budget: string;
  budgetValue: number;
  location: string;
  use: string;
  condition: string;
  requiredBy: string;
  buyer: string;
  postedDaysAgo: number;
  offers: number;
  notes: string;
}

export const WANTED: WantedPost[] = [
  {
    id: "w-pet-500",
    title: "WANTED: PET Plastic Scrap",
    category: "plastic",
    quantity: "500 kg",
    budget: "Up to 350,000 MMK",
    budgetValue: 350000,
    location: "Yangon",
    use: "Plastic manufacturing",
    condition: "Scrap / Requires Processing",
    requiredBy: "30 Aug 2026",
    buyer: "EcoBag Myanmar",
    postedDaysAgo: 1,
    offers: 4,
    notes: "Baled material preferred. We can collect from Yangon industrial zones with our own truck.",
  },
  {
    id: "w-cardboard-1000",
    title: "WANTED: Cardboard Boxes",
    category: "paper",
    quantity: "1,000 pieces",
    budget: "200–400 MMK/unit",
    budgetValue: 400000,
    location: "Mandalay",
    use: "Product shipping",
    condition: "Good or better",
    requiredBy: "25 Aug 2026",
    buyer: "Shwe Online Retail",
    postedDaysAgo: 2,
    offers: 6,
    notes: "Boxes must be dry and flat-packed. Repeat monthly requirement if quality is consistent.",
  },
  {
    id: "w-wood-100",
    title: "WANTED: Wood Offcuts",
    category: "wood",
    quantity: "100 kg",
    budget: "150,000 MMK",
    budgetValue: 150000,
    location: "Yangon",
    use: "Furniture production",
    condition: "Good",
    requiredBy: "28 Aug 2026",
    buyer: "Teak & Twine Studio",
    postedDaysAgo: 3,
    offers: 3,
    notes: "Hardwood preferred, minimum 30cm usable length.",
  },
  {
    id: "w-plastic-200",
    title: "WANTED: Plastic Scrap",
    category: "plastic",
    quantity: "200 kg",
    budget: "150,000 MMK",
    budgetValue: 150000,
    location: "Yangon",
    use: "Injection moulding inputs",
    condition: "Scrap / Requires Processing",
    requiredBy: "5 Sep 2026",
    buyer: "Mingalar Plastics Works",
    postedDaysAgo: 1,
    offers: 2,
    notes: "HDPE or PP regrind acceptable. Sample required before purchase.",
  },
  {
    id: "w-cotton-60",
    title: "WANTED: Cotton Fabric Surplus",
    category: "textile",
    quantity: "60 kg",
    budget: "Up to 300,000 MMK",
    budgetValue: 300000,
    location: "Yangon",
    use: "Tote bag production",
    condition: "New / Unused",
    requiredBy: "1 Sep 2026",
    buyer: "Yangon Craft Collective",
    postedDaysAgo: 4,
    offers: 5,
    notes: "Natural or undyed shades preferred.",
  },
  {
    id: "w-pallets-80",
    title: "WANTED: Wooden Pallets",
    category: "wood",
    quantity: "80 pallets",
    budget: "4,000 MMK/unit",
    budgetValue: 320000,
    location: "Bago",
    use: "Warehouse handling",
    condition: "Used",
    requiredBy: "10 Sep 2026",
    buyer: "Bago Agro Logistics",
    postedDaysAgo: 6,
    offers: 2,
    notes: "Four-way entry pallets only.",
  },
  {
    id: "w-aluminium-300",
    title: "WANTED: Aluminium Scrap",
    category: "metal",
    quantity: "300 kg",
    budget: "Up to 1,100,000 MMK",
    budgetValue: 1100000,
    location: "Yangon",
    use: "Casting and smelting",
    condition: "Scrap / Requires Processing",
    requiredBy: "18 Sep 2026",
    buyer: "Ayeyar Foundry",
    postedDaysAgo: 5,
    offers: 3,
    notes: "Clean extrusion scrap only, no mixed metals.",
  },
  {
    id: "w-glass-1500",
    title: "WANTED: Glass Bottles",
    category: "glass",
    quantity: "1,500 pieces",
    budget: "300 MMK/unit",
    budgetValue: 450000,
    location: "Yangon",
    use: "Kombucha bottling",
    condition: "Like New",
    requiredBy: "12 Sep 2026",
    buyer: "Golden Ferment Co.",
    postedDaysAgo: 7,
    offers: 1,
    notes: "330ml clear bottles, washed and crated.",
  },
];

export const wantedById = (id: string) => WANTED.find((w) => w.id === id);

export type TxStatus =
  | "Request Sent"
  | "Seller Responded"
  | "Inspection / Negotiation"
  | "Deal Created"
  | "Transaction QR Generated"
  | "Pickup / Delivery"
  | "Seller Confirms Sale"
  | "Completed";

export const TX_FLOW: TxStatus[] = [
  "Request Sent",
  "Seller Responded",
  "Inspection / Negotiation",
  "Deal Created",
  "Transaction QR Generated",
  "Pickup / Delivery",
  "Seller Confirms Sale",
  "Completed",
];

export interface Transaction {
  id: string;
  buyer: string;
  seller: string;
  sellerId: string;
  material: string;
  category: CategoryId;
  quantity: string;
  value: number;
  status: TxStatus;
  date: string;
  verified: boolean;
}

export const TRANSACTIONS: Transaction[] = [
  {
    id: "TXN-20481",
    buyer: "EcoBag Myanmar",
    seller: "Yangon Circular Plastics",
    sellerId: "yangon-circular-plastics",
    material: "PET Plastic Scrap",
    category: "plastic",
    quantity: "500 kg",
    value: 300000,
    status: "Transaction QR Generated",
    date: "14 Aug 2026",
    verified: false,
  },
  {
    id: "TXN-20476",
    buyer: "Shwe Online Retail",
    seller: "EcoBox Myanmar",
    sellerId: "ecobox-myanmar",
    material: "Corrugated Cardboard Boxes",
    category: "paper",
    quantity: "800 boxes",
    value: 240000,
    status: "Completed",
    date: "11 Aug 2026",
    verified: true,
  },
  {
    id: "TXN-20470",
    buyer: "Teak & Twine Studio",
    seller: "GreenWood Manufacturing",
    sellerId: "greenwood-manufacturing",
    material: "Wood Offcuts",
    category: "wood",
    quantity: "120 kg",
    value: 156000,
    status: "Completed",
    date: "9 Aug 2026",
    verified: true,
  },
  {
    id: "TXN-20465",
    buyer: "Ayeyar Foundry",
    seller: "Myanmar Metal Recovery",
    sellerId: "myanmar-metal-recovery",
    material: "Aluminum Offcuts",
    category: "metal",
    quantity: "250 kg",
    value: 950000,
    status: "Pickup / Delivery",
    date: "13 Aug 2026",
    verified: false,
  },
  {
    id: "TXN-20458",
    buyer: "Yangon Craft Collective",
    seller: "Green Stitch Textile",
    sellerId: "green-stitch",
    material: "Cotton Fabric Surplus",
    category: "textile",
    quantity: "60 kg",
    value: 270000,
    status: "Completed",
    date: "6 Aug 2026",
    verified: true,
  },
  {
    id: "TXN-20450",
    buyer: "Golden Ferment Co.",
    seller: "Yangon Glass Supply",
    sellerId: "yangon-glass-supply",
    material: "Glass Bottles",
    category: "glass",
    quantity: "1,000 pieces",
    value: 350000,
    status: "Inspection / Negotiation",
    date: "12 Aug 2026",
    verified: false,
  },
  {
    id: "TXN-20441",
    buyer: "Mingalar Plastics Works",
    seller: "Yangon Circular Plastics",
    sellerId: "yangon-circular-plastics",
    material: "Plastic Packaging Surplus",
    category: "plastic",
    quantity: "90 kg",
    value: 198000,
    status: "Completed",
    date: "2 Aug 2026",
    verified: true,
  },
  {
    id: "TXN-20433",
    buyer: "Shwe Interiors",
    seller: "CircularBuild Myanmar",
    sellerId: "circularbuild-myanmar",
    material: "Excess Ceramic Tiles",
    category: "construction",
    quantity: "40 boxes",
    value: 1000000,
    status: "Completed",
    date: "29 Jul 2026",
    verified: true,
  },
];

export interface Review {
  id: string;
  businessId: string;
  buyer: string;
  rating: number;
  accuracy: number;
  quality: number;
  communication: number;
  reliability: number;
  text: string;
  date: string;
  material: string;
}

export const REVIEWS: Review[] = [
  {
    id: "r1",
    businessId: "yangon-circular-plastics",
    buyer: "EcoBag Myanmar",
    rating: 5,
    accuracy: 5,
    quality: 5,
    communication: 5,
    reliability: 4,
    text: "Bales matched the listing weight exactly and loading was ready when we arrived. Third purchase from them.",
    date: "2 Aug 2026",
    material: "PET Plastic Scrap",
  },
  {
    id: "r2",
    businessId: "ecobox-myanmar",
    buyer: "Shwe Online Retail",
    rating: 5,
    accuracy: 5,
    quality: 4,
    communication: 5,
    reliability: 5,
    text: "Boxes were flat-packed and dry as described. Clear communication on collection time.",
    date: "11 Aug 2026",
    material: "Corrugated Cardboard Boxes",
  },
  {
    id: "r3",
    businessId: "green-stitch",
    buyer: "Yangon Craft Collective",
    rating: 5,
    accuracy: 5,
    quality: 5,
    communication: 4,
    reliability: 5,
    text: "Fabric quality was better than expected for surplus stock. Will buy again next season.",
    date: "6 Aug 2026",
    material: "Cotton Fabric Surplus",
  },
  {
    id: "r4",
    businessId: "greenwood-manufacturing",
    buyer: "Teak & Twine Studio",
    rating: 4,
    accuracy: 4,
    quality: 5,
    communication: 4,
    reliability: 4,
    text: "Good mix of usable lengths. A few pieces shorter than expected but overall strong value.",
    date: "9 Aug 2026",
    material: "Wood Offcuts",
  },
  {
    id: "r5",
    businessId: "myanmar-metal-recovery",
    buyer: "Ayeyar Foundry",
    rating: 5,
    accuracy: 5,
    quality: 5,
    communication: 4,
    reliability: 5,
    text: "Clean scrap, weighed in front of us on a certified scale. Very professional.",
    date: "28 Jul 2026",
    material: "Aluminum Offcuts",
  },
  {
    id: "r6",
    businessId: "circularbuild-myanmar",
    buyer: "Shwe Interiors",
    rating: 5,
    accuracy: 5,
    quality: 5,
    communication: 5,
    reliability: 5,
    text: "Same batch number across all boxes, exactly as listed. Saved our renovation budget.",
    date: "29 Jul 2026",
    material: "Excess Ceramic Tiles",
  },
];

export const reviewsFor = (businessId: string) =>
  REVIEWS.filter((r) => r.businessId === businessId);

export const PLATFORM_STATS = {
  businesses: 248,
  buyers: 1245,
  activeListings: 2830,
  completedTransactions: 684,
  transactionValue: "85.6M MMK",
  platformRevenue: "1.7M MMK",
  materialsExchanged: "12.4 Tons",
};

export const MONTHLY_VALUE = [
  { month: "Feb", value: 6.2, transactions: 41 },
  { month: "Mar", value: 7.8, transactions: 55 },
  { month: "Apr", value: 9.1, transactions: 63 },
  { month: "May", value: 11.4, transactions: 79 },
  { month: "Jun", value: 13.2, transactions: 94 },
  { month: "Jul", value: 16.7, transactions: 118 },
  { month: "Aug", value: 21.2, transactions: 134 },
];

export const CATEGORY_SALES = [
  { category: "Textile", tons: 4.2, value: 18.4 },
  { category: "Plastic", tons: 3.1, value: 21.6 },
  { category: "Paper", tons: 2.3, value: 12.1 },
  { category: "Metal", tons: 1.8, value: 19.8 },
  { category: "Wood", tons: 0.7, value: 5.4 },
  { category: "Glass", tons: 0.2, value: 3.6 },
  { category: "Rubber", tons: 0.1, value: 1.4 },
  { category: "Construction", tons: 1.1, value: 3.3 },
];

export const SELLER_STATS = {
  totalSales: "5,600,000 MMK",
  completed: 31,
  activeListings: 47,
  offersReceived: 23,
  rating: 4.8,
  inventoryValue: "8,500,000 MMK",
};

export const SELLER_NOTIFICATIONS = [
  { title: "New buyer inquiry", body: "EcoBag Myanmar asked about PET Plastic Scrap", time: "8m ago", type: "inquiry" },
  { title: "New wanted request matches your stock", body: "WANTED: 200kg Plastic Scrap — Yangon", time: "42m ago", type: "match" },
  { title: "Buyer accepted your offer", body: "Mingalar Plastics Works accepted 198,000 MMK", time: "3h ago", type: "offer" },
  { title: "Transaction completed", body: "TXN-20441 confirmed and verified", time: "1d ago", type: "transaction" },
  { title: "Listing expiring soon", body: "HDPE Plastic Sheets expires in 3 days", time: "1d ago", type: "listing" },
  { title: "Low inventory", body: "Plastic Packaging Surplus below 20kg", time: "2d ago", type: "inventory" },
];

export const BUYER_NOTIFICATIONS = [
  { title: "New seller response", body: "Yangon Circular Plastics responded to your request", time: "12m ago", type: "response" },
  { title: "AI match found", body: "EcoMatch AI found 3 suppliers for your cardboard request", time: "1h ago", type: "match" },
  { title: "Deal confirmed", body: "TXN-20481 deal created — QR ready", time: "5h ago", type: "deal" },
  { title: "Review available", body: "Leave a verified review for TXN-20476", time: "2d ago", type: "review" },
];

export const formatMMK = (n: number) => `${n.toLocaleString("en-US")} MMK`;

export const priceLabel = (l: Listing) =>
  l.price === null ? "Negotiable" : `${l.price.toLocaleString("en-US")} MMK/${l.priceUnit}`;
