// This file is automatically generated. Do not edit it directly.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.15";
  };
  graphql_public: {
    Tables: {
      [_ in never]: never;
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      graphql: {
        Args: {
          extensions?: Json;
          operationName?: string;
          query?: string;
          variables?: Json;
        };
        Returns: Json;
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
  public: {
    Tables: {
      businesses: {
        Row: {
          categories: Database["public"]["Enums"]["category_id"][];
          contact: Json;
          created_at: string;
          description: string;
          hours: string;
          id: string;
          industry: string;
          initials: string;
          location: string;
          name: string;
          rating: number;
          since: number;
          social_links: Json;
          transactions: number;
          user_id: string;
          verified: boolean;
          website: string | null;
        };
        Insert: {
          categories?: Database["public"]["Enums"]["category_id"][];
          contact?: Json;
          created_at?: string;
          description: string;
          hours: string;
          id?: string;
          industry: string;
          initials: string;
          location: string;
          name: string;
          rating?: number;
          since: number;
          social_links?: Json;
          transactions?: number;
          user_id: string;
          verified?: boolean;
          website?: string | null;
        };
        Update: {
          categories?: Database["public"]["Enums"]["category_id"][];
          contact?: Json;
          created_at?: string;
          description?: string;
          hours?: string;
          id?: string;
          industry?: string;
          initials?: string;
          location?: string;
          name?: string;
          rating?: number;
          since?: number;
          social_links?: Json;
          transactions?: number;
          user_id?: string;
          verified?: boolean;
          website?: string | null;
        };
        Relationships: [];
      };
      listings: {
        Row: {
          available_from: string;
          category: Database["public"]["Enums"]["category_id"];
          composition: string;
          condition: Database["public"]["Enums"]["condition_type"];
          created_at: string;
          description: string;
          featured: boolean;
          id: string;
          inquiries: number;
          location: string;
          material_type: Database["public"]["Enums"]["material_type"];
          min_order: string;
          pickup_available: boolean;
          popularity: number;
          price: number | null;
          price_unit: string;
          quantity: number;
          requires_processing: boolean;
          seller_id: string;
          status: Database["public"]["Enums"]["listing_status"];
          title: string;
          unit: string;
          uses: string[];
          views: number;
        };
        Insert: {
          available_from: string;
          category: Database["public"]["Enums"]["category_id"];
          composition: string;
          condition: Database["public"]["Enums"]["condition_type"];
          created_at?: string;
          description: string;
          featured?: boolean;
          id?: string;
          inquiries?: number;
          location: string;
          material_type: Database["public"]["Enums"]["material_type"];
          min_order: string;
          pickup_available?: boolean;
          popularity?: number;
          price?: number | null;
          price_unit: string;
          quantity: number;
          requires_processing?: boolean;
          seller_id: string;
          status?: Database["public"]["Enums"]["listing_status"];
          title: string;
          unit: string;
          uses?: string[];
          views?: number;
        };
        Update: {
          available_from?: string;
          category?: Database["public"]["Enums"]["category_id"];
          composition?: string;
          condition?: Database["public"]["Enums"]["condition_type"];
          created_at?: string;
          description?: string;
          featured?: boolean;
          id?: string;
          inquiries?: number;
          location?: string;
          material_type?: Database["public"]["Enums"]["material_type"];
          min_order?: string;
          pickup_available?: boolean;
          popularity?: number;
          price?: number | null;
          price_unit?: string;
          quantity?: number;
          requires_processing?: boolean;
          seller_id?: string;
          status?: Database["public"]["Enums"]["listing_status"];
          title?: string;
          unit?: string;
          uses?: string[];
          views?: number;
        };
        Relationships: [
          {
            foreignKeyName: "listings_seller_id_fkey";
            columns: ["seller_id"];
            isOneToOne: false;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
        ];
      };
      messenger_attachments: {
        Row: {
          created_at: string;
          id: string;
          kind: string;
          message_id: string;
          mime_type: string;
          name: string;
          size: number;
          storage_path: string | null;
          url: string;
        };
        Insert: {
          created_at?: string;
          id: string;
          kind?: string;
          message_id: string;
          mime_type: string;
          name: string;
          size: number;
          storage_path?: string | null;
          url: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          kind?: string;
          message_id?: string;
          mime_type?: string;
          name?: string;
          size?: number;
          storage_path?: string | null;
          url?: string;
        };
        Relationships: [
          {
            foreignKeyName: "messenger_attachments_message_id_fkey";
            columns: ["message_id"];
            isOneToOne: false;
            referencedRelation: "messenger_messages";
            referencedColumns: ["id"];
          },
        ];
      };
      messenger_conversations: {
        Row: {
          created_at: string;
          id: string;
          listing_ids: string[];
          request_ids: string[];
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          id: string;
          listing_ids?: string[];
          request_ids?: string[];
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          listing_ids?: string[];
          request_ids?: string[];
          updated_at?: string;
        };
        Relationships: [];
      };
      messenger_messages: {
        Row: {
          body: string;
          conversation_id: string;
          created_at: string;
          id: string;
          purchase_request: Json | null;
          sender_participant_id: string;
          sender_user_id: string;
          shared_listing: Json | null;
          status: string;
        };
        Insert: {
          body?: string;
          conversation_id: string;
          created_at?: string;
          id: string;
          purchase_request?: Json | null;
          sender_participant_id: string;
          sender_user_id: string;
          shared_listing?: Json | null;
          status?: string;
        };
        Update: {
          body?: string;
          conversation_id?: string;
          created_at?: string;
          id?: string;
          purchase_request?: Json | null;
          sender_participant_id?: string;
          sender_user_id?: string;
          shared_listing?: Json | null;
          status?: string;
        };
        Relationships: [
          {
            foreignKeyName: "messenger_messages_conversation_id_fkey";
            columns: ["conversation_id"];
            isOneToOne: false;
            referencedRelation: "messenger_conversations";
            referencedColumns: ["id"];
          },
        ];
      };
      messenger_participants: {
        Row: {
          avatar_text: string;
          conversation_id: string;
          created_at: string;
          image_url: string | null;
          name: string;
          online: boolean;
          participant_id: string;
          role: string;
          user_id: string;
        };
        Insert: {
          avatar_text: string;
          conversation_id: string;
          created_at?: string;
          image_url?: string | null;
          name: string;
          online?: boolean;
          participant_id: string;
          role: string;
          user_id: string;
        };
        Update: {
          avatar_text?: string;
          conversation_id?: string;
          created_at?: string;
          image_url?: string | null;
          name?: string;
          online?: boolean;
          participant_id?: string;
          role?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "messenger_participants_conversation_id_fkey";
            columns: ["conversation_id"];
            isOneToOne: false;
            referencedRelation: "messenger_conversations";
            referencedColumns: ["id"];
          },
        ];
      };
      messenger_reads: {
        Row: {
          conversation_id: string;
          last_read_at: string;
          participant_id: string;
          user_id: string;
        };
        Insert: {
          conversation_id: string;
          last_read_at?: string;
          participant_id: string;
          user_id: string;
        };
        Update: {
          conversation_id?: string;
          last_read_at?: string;
          participant_id?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "messenger_reads_conversation_id_fkey";
            columns: ["conversation_id"];
            isOneToOne: false;
            referencedRelation: "messenger_conversations";
            referencedColumns: ["id"];
          },
        ];
      };
      orders: {
        Row: {
          accepted_at: string | null;
          auto_accepted: boolean;
          buyer_fee: number;
          buyer_id: string;
          buyer_name: string;
          buyer_total: number;
          category: Database["public"]["Enums"]["category_id"];
          created_at: string;
          delivered_at: string | null;
          delivery_fee: number;
          dispute_reason: string | null;
          dispute_resolution: string | null;
          dispute_resolved_at: string | null;
          id: string;
          inspection_deadline: string | null;
          listing_id: string;
          listing_title: string;
          material_price: number;
          order_number: number;
          paid_at: string | null;
          payment_ref: string | null;
          payment_status: Database["public"]["Enums"]["payment_status"];
          payout_at: string | null;
          payout_ref: string | null;
          payout_status: Database["public"]["Enums"]["payout_status"];
          platform_revenue: number;
          quantity: number;
          seller_business_id: string;
          seller_fee: number;
          seller_name: string;
          seller_net: number;
          status: Database["public"]["Enums"]["order_status"];
          tax: number;
          unit: string;
          unit_price: number;
          updated_at: string;
        };
        Insert: {
          accepted_at?: string | null;
          auto_accepted?: boolean;
          buyer_fee?: number;
          buyer_id: string;
          buyer_name: string;
          buyer_total: number;
          category: Database["public"]["Enums"]["category_id"];
          created_at?: string;
          delivered_at?: string | null;
          delivery_fee?: number;
          dispute_reason?: string | null;
          dispute_resolution?: string | null;
          dispute_resolved_at?: string | null;
          id?: string;
          inspection_deadline?: string | null;
          listing_id: string;
          listing_title: string;
          material_price: number;
          order_number?: number;
          paid_at?: string | null;
          payment_ref?: string | null;
          payment_status?: Database["public"]["Enums"]["payment_status"];
          payout_at?: string | null;
          payout_ref?: string | null;
          payout_status?: Database["public"]["Enums"]["payout_status"];
          platform_revenue?: number;
          quantity: number;
          seller_business_id: string;
          seller_fee?: number;
          seller_name: string;
          seller_net: number;
          status?: Database["public"]["Enums"]["order_status"];
          tax?: number;
          unit: string;
          unit_price: number;
          updated_at?: string;
        };
        Update: {
          accepted_at?: string | null;
          auto_accepted?: boolean;
          buyer_fee?: number;
          buyer_id?: string;
          buyer_name?: string;
          buyer_total?: number;
          category?: Database["public"]["Enums"]["category_id"];
          created_at?: string;
          delivered_at?: string | null;
          delivery_fee?: number;
          dispute_reason?: string | null;
          dispute_resolution?: string | null;
          dispute_resolved_at?: string | null;
          id?: string;
          inspection_deadline?: string | null;
          listing_id?: string;
          listing_title?: string;
          material_price?: number;
          order_number?: number;
          paid_at?: string | null;
          payment_ref?: string | null;
          payment_status?: Database["public"]["Enums"]["payment_status"];
          payout_at?: string | null;
          payout_ref?: string | null;
          payout_status?: Database["public"]["Enums"]["payout_status"];
          platform_revenue?: number;
          quantity?: number;
          seller_business_id?: string;
          seller_fee?: number;
          seller_name?: string;
          seller_net?: number;
          status?: Database["public"]["Enums"]["order_status"];
          tax?: number;
          unit?: string;
          unit_price?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "orders_listing_id_fkey";
            columns: ["listing_id"];
            isOneToOne: false;
            referencedRelation: "listings";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "orders_seller_business_id_fkey";
            columns: ["seller_business_id"];
            isOneToOne: false;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
        ];
      };
      profiles: {
        Row: {
          created_at: string;
          full_name: string;
          id: string;
        };
        Insert: {
          created_at?: string;
          full_name: string;
          id: string;
        };
        Update: {
          created_at?: string;
          full_name?: string;
          id?: string;
        };
        Relationships: [];
      };
      purchase_requests: {
        Row: {
          agreed_total: number | null;
          agreed_unit_price: number | null;
          buyer_id: string;
          buyer_name: string;
          counter_delivery_fee: number | null;
          counter_note: string | null;
          counter_unit_price: number | null;
          created_at: string;
          fulfillment: string;
          id: string;
          listing_id: string;
          listing_title: string;
          message: string;
          offered_price: number;
          order_id: string | null;
          preferred_date: string;
          quantity: number;
          seller_business_id: string;
          status: Database["public"]["Enums"]["purchase_request_status"];
          unit: string;
          updated_at: string;
        };
        Insert: {
          agreed_total?: number | null;
          agreed_unit_price?: number | null;
          buyer_id: string;
          buyer_name: string;
          counter_delivery_fee?: number | null;
          counter_note?: string | null;
          counter_unit_price?: number | null;
          created_at?: string;
          fulfillment?: string;
          id?: string;
          listing_id: string;
          listing_title: string;
          message?: string;
          offered_price: number;
          order_id?: string | null;
          preferred_date?: string;
          quantity: number;
          seller_business_id: string;
          status?: Database["public"]["Enums"]["purchase_request_status"];
          unit: string;
          updated_at?: string;
        };
        Update: {
          agreed_total?: number | null;
          agreed_unit_price?: number | null;
          buyer_id?: string;
          buyer_name?: string;
          counter_delivery_fee?: number | null;
          counter_note?: string | null;
          counter_unit_price?: number | null;
          created_at?: string;
          fulfillment?: string;
          id?: string;
          listing_id?: string;
          listing_title?: string;
          message?: string;
          offered_price?: number;
          order_id?: string | null;
          preferred_date?: string;
          quantity?: number;
          seller_business_id?: string;
          status?: Database["public"]["Enums"]["purchase_request_status"];
          unit?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "purchase_requests_listing_id_fkey";
            columns: ["listing_id"];
            isOneToOne: false;
            referencedRelation: "listings";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "purchase_requests_seller_business_id_fkey";
            columns: ["seller_business_id"];
            isOneToOne: false;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
        ];
      };
      user_roles: {
        Row: {
          created_at: string;
          id: string;
          role: Database["public"]["Enums"]["app_role"];
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          role: Database["public"]["Enums"]["app_role"];
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          role?: Database["public"]["Enums"]["app_role"];
          user_id?: string;
        };
        Relationships: [];
      };
      wanted_posts: {
        Row: {
          budget: string;
          budget_value: number;
          buyer_name: string;
          category: Database["public"]["Enums"]["category_id"];
          condition: string;
          created_at: string;
          created_by: string | null;
          id: string;
          location: string;
          notes: string;
          offers_count: number;
          quantity: string;
          required_by: string;
          title: string;
          use: string;
        };
        Insert: {
          budget: string;
          budget_value: number;
          buyer_name: string;
          category: Database["public"]["Enums"]["category_id"];
          condition: string;
          created_at?: string;
          created_by?: string | null;
          id?: string;
          location: string;
          notes: string;
          offers_count?: number;
          quantity: string;
          required_by: string;
          title: string;
          use: string;
        };
        Update: {
          budget?: string;
          budget_value?: number;
          buyer_name?: string;
          category?: Database["public"]["Enums"]["category_id"];
          condition?: string;
          created_at?: string;
          created_by?: string | null;
          id?: string;
          location?: string;
          notes?: string;
          offers_count?: number;
          quantity?: string;
          required_by?: string;
          title?: string;
          use?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      has_role: {
        Args: {
          _role: Database["public"]["Enums"]["app_role"];
          _user_id: string;
        };
        Returns: boolean;
      };
      increment_listing_views: {
        Args: { listing_id: string };
        Returns: undefined;
      };
    };
    Enums: {
      app_role: "admin" | "moderator" | "user";
      category_id:
        | "textile"
        | "plastic"
        | "paper"
        | "metal"
        | "wood"
        | "glass"
        | "rubber"
        | "construction"
        | "industrial"
        | "other";
      condition_type:
        | "New / Unused"
        | "Like New"
        | "Good"
        | "Minor Defect"
        | "Used"
        | "Scrap / Requires Processing";
      listing_status: "Active" | "Reserved" | "Sold Out" | "Hidden";
      material_type:
        | "Reusable Surplus"
        | "Production Surplus"
        | "Offcut"
        | "Excess Inventory"
        | "Recyclable Material"
        | "Scrap Material"
        | "Packaging Surplus"
        | "Unused Stock";
      order_status:
        | "PENDING_PAYMENT"
        | "PAID"
        | "PREPARING"
        | "SHIPPED"
        | "DELIVERED"
        | "COMPLETED"
        | "DISPUTED"
        | "REFUNDED"
        | "CANCELLED";
      payment_status: "UNPAID" | "PAID" | "FAILED" | "REFUNDED";
      payout_status: "NOT_ELIGIBLE" | "PENDING" | "PAID";
      purchase_request_status: "Pending" | "Accepted" | "Countered" | "Rejected" | "Completed";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    keyof DefaultSchema["Enums"] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    keyof DefaultSchema["CompositeTypes"] | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {
      app_role: ["admin", "moderator", "user"],
      category_id: [
        "textile",
        "plastic",
        "paper",
        "metal",
        "wood",
        "glass",
        "rubber",
        "construction",
        "industrial",
        "other",
      ],
      condition_type: [
        "New / Unused",
        "Like New",
        "Good",
        "Minor Defect",
        "Used",
        "Scrap / Requires Processing",
      ],
      listing_status: ["Active", "Reserved", "Sold Out", "Hidden"],
      material_type: [
        "Reusable Surplus",
        "Production Surplus",
        "Offcut",
        "Excess Inventory",
        "Recyclable Material",
        "Scrap Material",
        "Packaging Surplus",
        "Unused Stock",
      ],
      order_status: [
        "PENDING_PAYMENT",
        "PAID",
        "PREPARING",
        "SHIPPED",
        "DELIVERED",
        "COMPLETED",
        "DISPUTED",
        "REFUNDED",
        "CANCELLED",
      ],
      payment_status: ["UNPAID", "PAID", "FAILED", "REFUNDED"],
      payout_status: ["NOT_ELIGIBLE", "PENDING", "PAID"],
      purchase_request_status: ["Pending", "Accepted", "Countered", "Rejected", "Completed"],
    },
  },
} as const;
